"""initial

Revision ID: b6ff1a0c0879
Revises: 
Create Date: 2026-04-28 08:16:19.278360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6ff1a0c0879'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(length=200), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=200), nullable=True),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('inscricao_estadual', sa.String(length=30), nullable=True),
    sa.Column('inscricao_municipal', sa.String(length=30), nullable=True),
    sa.Column('cnae_principal', sa.String(length=10), nullable=False),
    sa.Column('regime_tributario', sa.String(length=30), nullable=False),
    sa.Column('posicao_cadeia', sa.String(length=20), nullable=False),
    sa.Column('logradouro', sa.String(length=200), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('responsavel_nome', sa.String(length=150), nullable=True),
    sa.Column('responsavel_cpf', sa.String(length=14), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('grupos_tributarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('lei_base', sa.String(length=200), nullable=True),
    sa.Column('tabela_sped', sa.String(length=50), nullable=True),
    sa.Column('url_tabela_sped', sa.Text(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('logs_atualizacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tabela_sped', sa.String(length=20), nullable=True),
    sa.Column('versao', sa.String(length=20), nullable=True),
    sa.Column('data_atualizacao_rfb', sa.Date(), nullable=True),
    sa.Column('data_importacao', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('registros_inseridos', sa.Integer(), nullable=True),
    sa.Column('registros_atualizados', sa.Integer(), nullable=True),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.Column('executado_por', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('senha_hash', sa.String(length=256), nullable=False),
    sa.Column('perfil', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('ultimo_acesso', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('consultas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('tipo_consulta', sa.String(length=20), nullable=False),
    sa.Column('origem', sa.String(length=20), nullable=True),
    sa.Column('ncm_consultado', sa.String(length=10), nullable=True),
    sa.Column('descricao_produto', sa.String(length=500), nullable=True),
    sa.Column('codigo_produto', sa.String(length=50), nullable=True),
    sa.Column('codigo_nbm', sa.String(length=15), nullable=True),
    sa.Column('codigo_cest', sa.String(length=10), nullable=True),
    sa.Column('monofasico', sa.Boolean(), nullable=True),
    sa.Column('grupo_tributario', sa.String(length=100), nullable=True),
    sa.Column('lei_aplicada', sa.String(length=300), nullable=True),
    sa.Column('cst_atual', sa.String(length=3), nullable=True),
    sa.Column('cst_sugerido', sa.String(length=3), nullable=True),
    sa.Column('cfop_sugerido', sa.String(length=5), nullable=True),
    sa.Column('pis_aliquota', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('cofins_aliquota', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('posicao_cadeia', sa.String(length=20), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('inconsistencia_detectada', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'ncm_consultado', name='unique_empresa_ncm')
    )
    op.create_table('lotes_consulta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('nome_lote', sa.String(length=200), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('total_itens', sa.Integer(), nullable=True),
    sa.Column('itens_monofasicos', sa.Integer(), nullable=True),
    sa.Column('itens_nao_monofasicos', sa.Integer(), nullable=True),
    sa.Column('itens_com_inconsistencia', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('concluido_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ncms_tributarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ncm', sa.String(length=10), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('grupo_tributario_id', sa.Integer(), nullable=True),
    sa.Column('monofasico', sa.Boolean(), nullable=False),
    sa.Column('tipo_referencia', sa.String(length=30), nullable=True),
    sa.Column('lei', sa.String(length=300), nullable=True),
    sa.Column('cst_entrada', sa.String(length=3), nullable=True),
    sa.Column('cst_saida', sa.String(length=3), nullable=True),
    sa.Column('cfop_entrada_simples', sa.String(length=5), nullable=True),
    sa.Column('cfop_saida_simples', sa.String(length=5), nullable=True),
    sa.Column('pis_aliquota_fabricante', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('cofins_aliquota_fabricante', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('pis_aliquota_varejista', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('cofins_aliquota_varejista', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('vigencia_inicio', sa.Date(), nullable=True),
    sa.Column('vigencia_fim', sa.Date(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('fonte_url', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['grupo_tributario_id'], ['grupos_tributarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ncm', 'vigencia_inicio', name='unique_ncm_vigencia')
    )
    op.create_table('usuario_empresa',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'empresa_id')
    )
    op.create_table('lote_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.Column('consulta_id', sa.Integer(), nullable=True),
    sa.Column('linha_original', sa.Integer(), nullable=True),
    sa.Column('ncm', sa.String(length=10), nullable=True),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('codigo_produto', sa.String(length=50), nullable=True),
    sa.Column('codigo_cest', sa.String(length=10), nullable=True),
    sa.Column('status_processamento', sa.String(length=20), nullable=True),
    sa.Column('mensagem_erro', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['consulta_id'], ['consultas.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes_consulta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lote_itens')
    op.drop_table('usuario_empresa')
    op.drop_table('ncms_tributarios')
    op.drop_table('lotes_consulta')
    op.drop_table('consultas')
    op.drop_table('usuarios')
    op.drop_table('logs_atualizacao')
    op.drop_table('grupos_tributarios')
    op.drop_table('empresas')
    # ### end Alembic commands ###
